strategy: WeightedRoundRobin
global_rate_limit:
  requests_per_second: 200
  burst_size: 1500

backends:
  backend1:
    url: "http://localhost:3001"
    weight: 100
    rate_limit:
      requests_per_second: 200
      burst_size: 150

  backend2:
    url: "http://localhost:3002"
    weight: 1
    rate_limit:
      requests_per_second: 2
      burst_size: 120

is_debug: true